name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v4.1.0
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{b687bb98-109d-4e47-b9cf-5bbc64afd340}}
      
